# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='usuario_factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Usuario'),
        ),
    ]
