# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 02:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_auto_20180906_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='usuario_factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
