# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-05 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_auto_20180924_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='usuario_factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Usuario'),
        ),
    ]
