# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-16 21:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_auto_20181105_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='usuario_factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
