# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 18:26
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_color', models.CharField(max_length=40)),
                ('file_color', models.FileField(upload_to='color')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50)),
                ('pais_producto', models.CharField(choices=[('USA', 'Estados Unidos'), ('COL', 'Colombia'), ('AUS', 'Australia'), ('ESP', 'España'), ('ITA', 'Italia'), ('GER', 'Alemania')], max_length=3)),
                ('ciudad_producto', models.CharField(choices=[('ORL', 'Orlando'), ('BOG', 'Bogotá'), ('MEL', 'Melbourne'), ('VAL', 'Valencia'), ('MIL', 'Milan'), ('BER', 'Berlin')], max_length=3)),
                ('precio_producto', models.IntegerField()),
                ('cantidad_producto', models.IntegerField()),
                ('descripcion_producto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Troquel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_troquel', models.CharField(max_length=40)),
                ('file_troquel', models.FileField(upload_to='svg')),
                ('size_troquel', models.IntegerField()),
                ('tipo_troquel', models.CharField(choices=[('YES', 'magnetized'), ('NO', 'not magnetized')], default='YES', max_length=3)),
                ('categoria_troquel', models.CharField(choices=[('', ''), ('LET', 'Letter'), ('THI', 'Things'), ('CAR', 'Cars and home'), ('FRU', 'Fruits'), ('PER', 'Persons'), ('SHE', 'SHEET')], default='none', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAdmin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('color', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'usuarioa',
                'verbose_name_plural': 'usuariosa',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_zona', models.CharField(max_length=40)),
                ('color_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminlio.Producto')),
                ('color_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminlio.Color')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='troquel_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminlio.Troquel'),
        ),
    ]
