# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlio', '0002_remove_usuarioadmin_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ciudad_producto',
            field=models.CharField(choices=[('', ''), ('ORL', 'Orlando'), ('BOG', 'Bogotá'), ('MEL', 'Melbourne'), ('VAL', 'Valencia'), ('MIL', 'Milan'), ('BER', 'Berlin')], default='none', max_length=3),
        ),
        migrations.AlterField(
            model_name='producto',
            name='pais_producto',
            field=models.CharField(choices=[('', ''), ('USA', 'Estados Unidos'), ('COL', 'Colombia'), ('AUS', 'Australia'), ('ESP', 'España'), ('ITA', 'Italia'), ('GER', 'Alemania')], default='none', max_length=3),
        ),
    ]
