# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlio', '0004_auto_20180907_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troquel',
            name='categoria_troquel',
            field=models.CharField(choices=[('', ''), ('IMA', 'Magnet'), ('CER', 'Pottery'), ('BIS', 'Catchpenny'), ('HOG', 'Home')], default='none', max_length=3),
        ),
    ]
