# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-29 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlio', '0005_auto_20180907_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base64images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_image', models.FileField(upload_to='basesixfor')),
            ],
        ),
    ]
