# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-21 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlio', '0006_base64images'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tamano_producto',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
