# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-16 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlio', '0007_producto_tamano_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='img_producto',
            field=models.FileField(blank=True, null=True, upload_to='svg'),
        ),
        migrations.AddField(
            model_name='producto',
            name='prev_producto',
            field=models.CharField(choices=[('', '----'), ('ZON', 'troquel'), ('IMG', 'imagen'), ('VID', 'video')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='producto',
            name='video_producto',
            field=models.FileField(blank=True, null=True, upload_to='svg'),
        ),
        migrations.AddField(
            model_name='troquel',
            name='editable_troquel',
            field=models.CharField(choices=[('', '----'), ('NO', 'No'), ('YES', 'Si')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='troquel',
            name='file_troquel',
            field=models.FileField(blank=True, null=True, upload_to='svg'),
        ),
    ]
