# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-19 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlio', '0008_auto_20181116_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='img_producto',
            field=models.FileField(blank=True, default='null', null=True, upload_to='svg'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='video_producto',
            field=models.FileField(blank=True, default='null', null=True, upload_to='svg'),
        ),
    ]
